name: Dockerized App Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build containers
        run: docker compose build

      - name: Start app + test stack
        run: docker compose up -d

      - name: Wait for selenium-hub to be ready
        run: |
           echo "Waiting for selenium-hub to be ready..."
            for i in {1..100}; do
              if docker logs selenium-grid-docker-selenium-hub-1 2>&1 | grep -q "Started Selenium Hub"; then
                echo "Selenium Hub is ready!"
                break
              fi
              sleep 2
            done

      - name: Log Selenium Grid Status
        run: |
          echo "Grid status:"
          curl -s http://localhost:4444/status | jq .

      - name: Print environment variables
        run: env

      - name: Show Docker networks
        run: docker network ls && docker network inspect bridge

      - name: Show Docker container status before tests
        run: docker ps -a

      - name: Show Docker container memory usage
        run: docker stats --no-stream --format "table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}"

      - name: Run tests in eatest
        run: docker exec eatest dotnet test /src/EAAppTest/EAAppTest.csproj --logger:trx --no-build --configuration Release

      - name: Show Docker container memory usage
        run: docker stats --no-stream --format "table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}"

      - name: Copy test results from container (if running)
        run: |
          mkdir -p test-results
          if docker ps -a --format '{{.Names}}' | grep -q '^eatest$'; then
            docker cp eatest:/src/EAAppTest/TestResults test-results || echo "Could not copy test results; container may have exited."
          else
            echo "eatest container is not running or has exited. Skipping docker cp."
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/TestResults/*.trx

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: 'test-results/TestResults/*.trx'

      - name: Show test container logs on failure
        if: failure()
        run: docker logs eatest

      - name: Show selenium hub logs on failure
        if: failure()
        run: docker logs selenium-grid-docker-selenium-hub-1

      - name: Show Docker container memory usage on failure
        if: failure()
        run: docker stats --no-stream --format "table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}"

